// Include tests generated by `build.rs`
mod lookup {
    include!(concat!(env!("OUT_DIR"), "/lookup.rs"));
}

mod browse {
    include!(concat!(env!("OUT_DIR"), "/browse.rs"));
}

mod search {
    include!(concat!(env!("OUT_DIR"), "/search.rs"));
}
